# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
        - localhost:9090

  - job_name: 'prometheus_grafana_server'
    scrape_interval: 5s
    static_configs:
      - targets:
        - localhost:9100

  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets:
        - localhost:3000

  - job_name: 'database_server'
    scrape_interval: 5s
    static_configs:
      - targets:
        - <database_instance_private_ip>:9100

        